### ISSUE TITLE
odd result

### ISSUE THREAD

**Issue by pcanal** [go-hep/groot-bench#2]
```
ReadCMS/ROOT-TreeBranch/Zlib-8     37.5s ± 1%
ReadCMS/ROOT-TreeReader/Zlib-8     26.1s ± 3%
```
This result is hard to understand.  TTreeReader introduced extra feature and thus extra cost and cannot/should-not be faster than direct access.   Do you understand what is unusual here?

**Comment by pcanal** [comment]
Also in 
```
ReadCMS/GoHEP/Zlib-8               19.2s ± 1%
ReadCMS/ROOT-TreeBranch/Zlib-8     37.5s ± 1%
ReadCMS/ROOT-TreeReader/Zlib-8     26.1s ± 3%
```
Is the go version reading all the branches/data or a subset? (it is not clear from reading the code)

**Comment by sbinet** [comment]
yes, `groot` is reading all the branches.
`rtree.NewReadVars(tree)` returns the complete set of "read-vars" associated to the given tree:
- https://godoc.org/go-hep.org/x/hep/groot/rtree#NewReadVars

one possible reason for TreeReader being faster in ReadCMS is that I don't explicitly read the leaves if `nMuon` or `nElecton` <= 0.
whereas, I suspect, in the TreeBranch case, even though the associated leaves will return empty for those events, the I/O layer will still be queried.

would that make sense?

**Comment by pcanal** [comment]
Yes it would.  Apparently there 20% of 0 electrons. and 85% of 0 muons.  Aka this is then not a "pure" performance comparison (work load is different) but more of a practical one (it might be easier to get performance when using RDF).

Does the go version have the same optimization as the RDF version?

**Comment by sbinet** [comment]
nope.
ATM, groot doesn't do lazy-loading as TreeReader or RDF do.

I'll split that benchmark b/w one that reads all the branches that are never empty (ie: all scalars)
and one that computes some pt-sum (or something).
